name: Deploy Backend to AWS Lambda

on:
  push:
    branches:
      - main
      - 49-bot-setup
    # paths:
    #   - "backend/**"

permissions:
  contents: write
  deployments: write

jobs:
  install-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          cd backend
          npm ci

      - name: Build the Project
        run: |
          cd backend
          npm run build

      - name: Add service json
        run: |
          cd backend
          echo '${{ secrets.SERVICE_JSON }}' > dist/service.json

      - name: Zip the Files
        run: |
          cd backend
          (cd dist && zip -r ../backend.zip .) && zip -ur backend.zip node_modules package.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: backend/backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: install-and-build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-package
          path: backend

      - name: Move ZIP file to root
        run: mv backend/backend.zip backend.zip

      - name: Deploy to AWS Lambda
        uses: docker://amazon/aws-cli
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        with:
          entrypoint: /usr/local/bin/aws
          args: >-
            lambda update-function-code
            --function-name ParentsAdminAPI
            --zip-file fileb://backend.zip

      - name: Notify GitHub of Deployment Status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'backend',
              required_contexts: []
            });

            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: 'success'
            });
